language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure.
sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/BuzzerExample
  - PLATFORMIO_CI_SRC=examples/DimmableLightExample
  - PLATFORMIO_CI_SRC=examples/DS6120SensorExample
  - PLATFORMIO_CI_SRC=examples/L298MotorControlExample
  - PLATFORMIO_CI_SRC=examples/LEDExample
  - PLATFORMIO_CI_SRC=examples/RelayExample
  - PLATFORMIO_CI_SRC=examples/ToggleSwitchExample
  - PLATFORMIO_CI_SRC=examples/REXExample
  - PLATFORMIO_CI_SRC=examples/ResetManagerExample
  - PLATFORMIO_CI_SRC=examples/TemperatureSensorExample

install:
  - pip install -U platformio

script:
  - platformio ci --lib="." --board=uno --board=megaatmega1280 --board=megaatmega2560 --board=micro --board=leonardo

notifications:
  email:
    on_success: change
    on_failure: change
